/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecommendedRouteImport } from './routes/recommended'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrendsSlugRouteImport } from './routes/trends.$slug'
import { Route as AdminTrendsRouteImport } from './routes/admin.trends'
import { Route as ApiPublicHooksPerfRegressionCheckRouteImport } from './routes/api/public/hooks/perf-regression-check'

const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendedRoute = RecommendedRouteImport.update({
  id: '/recommended',
  path: '/recommended',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsSlugRoute = TrendsSlugRouteImport.update({
  id: '/trends/$slug',
  path: '/trends/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrendsRoute = AdminTrendsRouteImport.update({
  id: '/admin/trends',
  path: '/admin/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksPerfRegressionCheckRoute =
  ApiPublicHooksPerfRegressionCheckRouteImport.update({
    id: '/api/public/hooks/perf-regression-check',
    path: '/api/public/hooks/perf-regression-check',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/glossary': typeof GlossaryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recommended': typeof RecommendedRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/vote': typeof VoteRoute
  '/admin/trends': typeof AdminTrendsRoute
  '/trends/$slug': typeof TrendsSlugRoute
  '/api/public/hooks/perf-regression-check': typeof ApiPublicHooksPerfRegressionCheckRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/glossary': typeof GlossaryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recommended': typeof RecommendedRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/vote': typeof VoteRoute
  '/admin/trends': typeof AdminTrendsRoute
  '/trends/$slug': typeof TrendsSlugRoute
  '/api/public/hooks/perf-regression-check': typeof ApiPublicHooksPerfRegressionCheckRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/archive': typeof ArchiveRoute
  '/auth': typeof AuthRoute
  '/glossary': typeof GlossaryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/recommended': typeof RecommendedRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/vote': typeof VoteRoute
  '/admin/trends': typeof AdminTrendsRoute
  '/trends/$slug': typeof TrendsSlugRoute
  '/api/public/hooks/perf-regression-check': typeof ApiPublicHooksPerfRegressionCheckRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/archive'
    | '/auth'
    | '/glossary'
    | '/pricing'
    | '/privacy'
    | '/recommended'
    | '/settings'
    | '/terms'
    | '/vote'
    | '/admin/trends'
    | '/trends/$slug'
    | '/api/public/hooks/perf-regression-check'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/archive'
    | '/auth'
    | '/glossary'
    | '/pricing'
    | '/privacy'
    | '/recommended'
    | '/settings'
    | '/terms'
    | '/vote'
    | '/admin/trends'
    | '/trends/$slug'
    | '/api/public/hooks/perf-regression-check'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/archive'
    | '/auth'
    | '/glossary'
    | '/pricing'
    | '/privacy'
    | '/recommended'
    | '/settings'
    | '/terms'
    | '/vote'
    | '/admin/trends'
    | '/trends/$slug'
    | '/api/public/hooks/perf-regression-check'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ArchiveRoute: typeof ArchiveRoute
  AuthRoute: typeof AuthRoute
  GlossaryRoute: typeof GlossaryRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RecommendedRoute: typeof RecommendedRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  VoteRoute: typeof VoteRoute
  AdminTrendsRoute: typeof AdminTrendsRoute
  TrendsSlugRoute: typeof TrendsSlugRoute
  ApiPublicHooksPerfRegressionCheckRoute: typeof ApiPublicHooksPerfRegressionCheckRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommended': {
      id: '/recommended'
      path: '/recommended'
      fullPath: '/recommended'
      preLoaderRoute: typeof RecommendedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends/$slug': {
      id: '/trends/$slug'
      path: '/trends/$slug'
      fullPath: '/trends/$slug'
      preLoaderRoute: typeof TrendsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/trends': {
      id: '/admin/trends'
      path: '/admin/trends'
      fullPath: '/admin/trends'
      preLoaderRoute: typeof AdminTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/perf-regression-check': {
      id: '/api/public/hooks/perf-regression-check'
      path: '/api/public/hooks/perf-regression-check'
      fullPath: '/api/public/hooks/perf-regression-check'
      preLoaderRoute: typeof ApiPublicHooksPerfRegressionCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ArchiveRoute: ArchiveRoute,
  AuthRoute: AuthRoute,
  GlossaryRoute: GlossaryRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RecommendedRoute: RecommendedRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  VoteRoute: VoteRoute,
  AdminTrendsRoute: AdminTrendsRoute,
  TrendsSlugRoute: TrendsSlugRoute,
  ApiPublicHooksPerfRegressionCheckRoute:
    ApiPublicHooksPerfRegressionCheckRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
